name: Application on Surge.sh

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy_Surge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      
      - name: Node.JS Environment
        uses: actions/setup-node@v1
      
      - name: Install Yarn
        run: yarn install

      - name: Build React App
        run: yarn build

      - name: Setup Surge
        run:  npm install -g surge

      - name: Deploy with surge
        run:  surge ./build http://bootcamp_practice_class2.surge.sh/ --token ${{secrets.SURGE_TOKEN2}}
